"""add cost tracking columns

Revision ID: 3611184d1964
Revises: 47cb1f38d83b
Create Date: 2026-02-06 03:09:11.613408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3611184d1964'
down_revision: Union[str, Sequence[str], None] = '47cb1f38d83b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('total_cost', sa.Float(), nullable=True))
    op.add_column('messages', sa.Column('input_tokens', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('output_tokens', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('cost', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'cost')
    op.drop_column('messages', 'output_tokens')
    op.drop_column('messages', 'input_tokens')
    op.drop_column('conversations', 'total_cost')
    # ### end Alembic commands ###
